{application,pod_app,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{pod_app_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[pod_app_app,pod_app_sup]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
